#!/usr/bin/perl

for ($idx = 0; $idx < scalar(@ARGV); $idx++) {
    $arg = $ARGV[$idx];

    if ($arg eq "-v") { $verbose = 1; }
    if ($arg eq "-date") { $importDate = $ARGV[$idx+1]; $idx++; next; }

    if ($arg eq "-suffix") { $suffix = $ARGV[$idx+1]; $idx++; next; }
}

require "scripts/options.pl";

if ( ! defined($importDate)) {
    print "\nPlease give me an import date as a parameter.\n\n";
    exit(0);
}

if (&db_exists(&option("dbName")."_".$importDate) != 1) { 
    print "\nERROR: database \"".&option("dbName")."_".$importDate."\" does not exist.\n";
    exit(1);
}

if ( ! defined($suffix)) { $suffix = "_cd"; }

$cmd = "echo \"show tables;\" | ".$myQ."_".$importDate." | grep '".$suffix."'";
@tables = `$cmd`;
chomp(@tables);

open M, "| ".$myV;

foreach (@tables) {
    print M "drop table ".$_.";\n";
}

close M;

print "\nDone.\n\n";

exit(0);
