#!/bin/sh

if [ "$1" != "-date" ] || [ "$2" = "" ]; then
    echo ""
    echo "usage: ./08_create_named_uniq -date <YYYYMMDD>"
    echo ""
    exit
fi

db=$2

if [ `uname` = "Darwin" ]; then
    u=""
else
    u="-u root --password=root "
fi

cat - <<EOF | mysql $u -vvv --local-infile ca_sos_$db 2>/dev/null

drop table if exists named_uniq;

create table named_uniq (
  pk int(11) DEFAULT NULL,
  naml varchar(200) DEFAULT NULL,
  namf varchar(45) DEFAULT NULL,
  namt varchar(10) DEFAULT NULL,
  nams varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) < 'A';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'A';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'B';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'C';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'D';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'E';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'F';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'G';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'H';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'I';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'J';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'K';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'L';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'M';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'N';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'O';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'P';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'Q';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'R';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'S';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'T';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'U';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'V';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'W';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'X';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'Y';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'Z';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) > 'Z' and substr(naml,1,1) < 'a';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'a';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'b';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'c';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'd';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'e';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'f';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'g';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'h';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'i';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'j';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'k';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'l';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'm';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'n';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'o';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'p';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'q';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'r';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 's';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 't';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'u';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'v';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'w';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'x';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'y';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) = 'z';
insert into named_uniq (naml, namf, nams, namt) select distinct naml, namf, nams, namt from named where substr(naml,1,1) > 'z';

update named_uniq cross join (select @pk:=0) as init set named_uniq.pk=@pk:=@pk+1;

alter table named_uniq add primary key (pk);

alter table named add index (naml, namf, namt, nams);

alter table named_uniq add index (naml, namf, namt, nams);

drop procedure if exists SetNamedUniqPkInfoNamed;

delimiter $$

create procedure SetNamedUniqPkInfoNamed()
begin
    
    declare max int;
    declare idx int default 0;

    select max(table_pk) into max from named;

    while idx <= max do
        select idx, idx+100000, now();
        update named n1, named_uniq n2 set n1.uniq_pk = n2.pk where n2.pk >= idx and n2.pk < (idx+100000)
            and n1.naml = n2.naml and n1.namf = n2.namf and n1.nams = n2.nams and n1.namt = n2.namt;
        set idx = idx + 100000;
    end while;

end $$

delimiter ;

call SetNamedUniqPkInfoNamed();

drop procedure SetNamedUniqPkInfoNamed;

EOF

