#!/bin/sh

if [ "$1" != "-date" ] || [ "$2" = "" ]; then
    echo ""
    echo "usage: ./08_create_named_uniq -date <YYYYMMDD>"
    echo ""
    exit
fi

db=$2

if [ `uname` = "Darwin" ]; then
    u=""
else
    u="-u root --password=root "
fi

if [ -d /tmp/named ]; then
    /bin/rm -rf /tmp/named
fi

mkdir /tmp/named
cd /tmp/named

echo ""
echo "set up the data for the named_uniq table"
echo ""

echo "select naml, namf, namt, nams from named;" | mysql $u --skip-column-names ca_sos_$db 2>dev.null > n1.txt

sort < n1.txt | sort | awk '{print NR"\t"$0}' > named_uniq

cat <<EOF | mysql $u -vvv --local-infile ca_sos_$db 2>/dev/null

create table `named_uniq` (
  `pk` int(11) DEFAULT NULL,
  `naml` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL,
  `namf` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `namt` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `nams` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

load data local infile '/tmp/named/named_uniq' into table named_uniq;
EOF

/bin/rm n1.txt named_uniq

echo ""
echo "recreate the named table with the uniq_pk value"
echo "

echo "select naml,namf,namt,nams,pk from named_uniq;" | \
    mysql $u --skip-column-names ca_sos_$db 2>/dev/null > n1.txt

echo "select naml,namf,namt,nams,table_name,table_pk,name_type from named;" | \
    mysql $u --skip-column-names ca_sos_20200615 2>/dev/null > n2.txt

cat n1.txt n2.txt | sort > n3.txt

awk 'BEGIN{FS="\t"}{if (NF == 4) fk=$4;
           if (NF == 7) print $5"\t"$6"\t"$7"\t"$1"\t"$2"\t"$3"\t"$4"\t"fk}' n3.txt > n4.txt

split --lines=10000 --suffix-length=4 n4.txt n4_

cat <<EOF | mysql $u -vvv ca_sos_$db 2>/dev/null

rename table named to named_bak;
create table `named` (
  `table_name` varchar(40) COLLATE utf8mb4_bin NOT NULL,
  `table_pk` int(11) NOT NULL,
  `name_type` varchar(6) COLLATE utf8mb4_bin NOT NULL,
  `naml` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL,
  `namf` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `namt` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `nams` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `names_pk` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8_general_cs;

EOF

/bin/ls -1 n4_* | \
    awk '{print "cp "$0" named";
          print "echo \"load data local infile '\''/tmp/named/named'\'' into table named;\" | \\";
          print "mysql '$u' --local-infile ca_sos_'$db'"}' | /bin/sh 2>/dev/null


# /bin/rm -rf /tmp/named

cat <<EOF | mysql $u -vvv ca_sos_$db
  alter table named_uniq add column smooth_pk int;
  alter table named_uniq add column smoothed varchar(299);
  create table named_smooth (pk int, name varchar(299), uniq_count int, named_count int, linked_to_pk int);
  alter table named_smooth add unique (name);
EOF

echo "creating smoothed strings..."
date

echo "select pk,concat(namf,' ',naml,' ',namt,' ',nams) from named_uniq;" | \
    mysql $u --skip-column-names ca_sos_$db | \
    tr '[A-Z]' '[a-z]' | \
    sed 's/[\.\,'\'']//g' | \
    sed 's/ $//g' | \
    awk 'BEGIN{FS="\t"}{print $2"\t"$1}' | \
    sed 's/^ *//' | \
    sed 's/  */ /g' | \
    awk 'BEGIN{FS="\t"}{print "update named_uniq set smoothed = '\''"$1"'\'' where pk = "$2";"}' | \
    mysql $u ca_sos_$db

date

cat <<EOF | mysql $u -vvv ca_sos_$db
  replace into named_smooth (name) select smoothed from named_uniq;
  update named_smooth cross join (select @pk:=0) as init set named_smooth.pk=@pk:=@pk+1;
  alter table named_uniq add index (smoothed);
  alter table named_smooth add primary key (pk);
EOF

echo "setting smooth_pk back in uniq table..."
date

echo "select pk, name from named_smooth;" | \
    mysql $u --skip-column-names ca_sos_$db | \
    awk 'BEGIN{FS="\t"}{print "update named_uniq set smooth_pk = "$1" where smoothed = '\''"$2"'\'';"}' | \
    mysql $u ca_sos_$db

date

cat <<EOF | mysql $u -vvv ca_sos_$db
    alter table named_uniq drop column smoothed;
    alter table named_uniq add index (smooth_pk);
EOF

