#!/bin/sh

if [ "$1" != "-date" ] || [ "$2" = "" ]; then
    echo ""
    echo "usage: ./08_create_named_uniq -date <YYYYMMDD>"
    echo ""
    exit
fi

db=$2

echo "desc named_uniq;" | mysql --skip-column-names ca_sos_$db | tr '\t' ' ' | grep 'smooth_pk ' > /tmp/uniq_$$

if [ ! -s /tmp/uniq_$$ ]; then
    echo "alter table named_uniq add column smooth_pk int;" | mysql -vvv ca_sos_$db
fi

echo "desc named_uniq;" | mysql --skip-column-names ca_sos_$db | tr '\t' ' ' | grep 'smoothed ' > /tmp/uniq_$$

if [ ! -s /tmp/uniq_$$ ]; then
    echo "alter table named_uniq add column smoothed varchar(299);" | mysql -vvv ca_sos_$db
fi

echo ""
echo "creating smoothed strings in uniq table..."
date

count=1

while [ $count -gt 0 ];
do

    echo "select pk,concat(namf,' ',naml,' ',namt,' ',nams) from named_uniq where smoothed is NULL limit 10000;" | \
        mysql --skip-column-names ca_sos_$db | \
        tr '[A-Z]' '[a-z]' | \
        sed 's/[\.\,'\'']//g' | \
        sed 's/ $//g' | \
        awk 'BEGIN{FS="\t"}{print $2"\t"$1}' | \
        sed 's/^ *//' | \
        sed 's/  */ /g' | \
        awk 'BEGIN{FS="\t"}{print "update named_uniq set smoothed = '\''"$1"'\'' where pk = "$2";"}' | \
        mysql ca_sos_$db

    count=`echo "select count(0) from named_uniq where smoothed is not NULL;" | mysql --skip-column-names ca_sos_$db`

done

date

echo ""
echo "putting the smoothed strings into the smooth table..."
echo ""

echo "show tables;" | mysql --skip-column-names ca_sos_20200715 | tr '\t' ' ' | grep 'named_smooth' > /tmp/uniq_$$

if [ ! -s /tmp/uniq_$$ ]; then
    ( echo "create table named_smooth (pk int, name varchar(299), uniq_count int, named_count int, linked_to_pk int);" ;
      echo "alter table named_smooth add unique (name);" ) | mysql -vvv ca_sos_$db

cat - <<EOF | mysql $u -vvv ca_sos_$db

drop procedure if exists SetUniqIntoSmoothed;

delimiter $$

create procedure SetUniqIntoSmoothed()
begin
    
    declare max int;
    declare idx int default 0;

    select max(pk) into max from named_uniq;

    while idx <= max do
        select idx, idx+100000, now();
        replace into named_smooth (name) select smoothed from named_uniq where pk >= idx and pk < (idx+100000);
        set idx = idx + 100000;
    end while;

end $$

delimiter ;

call SetUniqIntoSmoothed();

update named_smooth cross join (select @pk:=0) as init set named_smooth.pk=@pk:=@pk+1;

alter table named_uniq add index (smoothed);

alter table named_smooth add primary key (pk);

EOF

echo ""
echo "setting smooth_pk back in uniq table..."
date

echo "select pk, name from named_smooth;" | \
    mysql $u --skip-column-names ca_sos_$db | \
    awk 'BEGIN{FS="\t"}{print "update named_uniq set smooth_pk = "$1" where smoothed = '\''"$2"'\'';"}' | \
    mysql $u ca_sos_$db

date

cat - <<EOF | mysql $u -vvv ca_sos_$db

alter table named_uniq drop column smoothed;

alter table named_uniq add index (smooth_pk);

EOF

exit
