#!/usr/bin/perl

require "scripts/options.pl";

$usage = "usage: ./09_move_database";

if (scalar(@ARGV) < 2) { print "\n".$usage."\n"; exit(0); }

$toDB = $ARGV[scalar(@ARGV)-1];
$fromDB = $ARGV[scalar(@ARGV)-2];

for ($idx = 0; $idx < scalar(@ARGV)-2; $idx++) {
    $arg = $ARGV[$idx];
 
    if ($arg eq "-date") { $importDate = $ARGV[$idx+1]; $idx++; next; }

    if ($arg eq "-v") { $verbose = 1; }
}

$cmd = "echo \"show tables;\" | ".$myQ."_".$importDate;
@tables = `$cmd`;
chomp(@tables);

open M, "| ".&option("mysql")." -u ".&option("dbUser")." --password=".&option("dbPwd")." -vvv";

print M "create database ".$toDB.";\n";

foreach (@tables) {
    $table = $_;

    print M "rename table ".$fromDB.".".$table." to ".$toDB.".".$table.";\n";
}

close M;

@nextTables = `$cmd`;
chomp(@nextTables);

if (scalar(@nextTables) == 0) {

    print "\nDatabase \"".$fromDB." is empty. Drop it? (^C to exit)";
    $r = <STDIN>;
    $cmd = "echo \"drop database ".$fromDB."\" | ".&option("mysql")." -u ".&option("dbUser")." --password=".&option("dbPwd")." -vvv";
    print `$cmd`;
}

print "\n";

exit(0);
